// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for macos - '
            'you can reconfigure this by running the FlutterFire CLI again.' // <-- Missing ;
            );
      case TargetPlatform.windows:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for windows - '
            'you can reconfigure this by running the FlutterFire CLI again.' // <-- Missing ;
            );
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.' // <-- Missing ;
            );
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.' // <-- Missing ;
            );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQNH_8AWNdIsL2r3idIcDeeKFVLfefb0',
    appId: '1:693029812993:web:115e17120762e822f9b900',
    messagingSenderId: '693029812993',
    projectId: 'jobseekapi',
    authDomain: 'jobseekapi.firebaseapp.com',
    storageBucket: 'jobseekapi.appspot.com',
    measurementId: 'G-ZSZQ724PXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOdHasSoM8AQce4EYKDABMZ799vs-YNg',
    appId: '1:693029812993:android:47c9b3a37abdbc88f9b900',
    messagingSenderId: '693029812993',
    projectId: 'jobseekapi',
    storageBucket: 'jobseekapi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42E02ysVr_XKQh9sM3U4DDdv_0jFFaC0',
    appId: '1:693029812993:ios:d42e31d70fa28e8cf9b900',
    messagingSenderId: '693029812993',
    projectId: 'jobseekapi',
    storageBucket: 'jobseekapi.appspot.com',
    iosBundleId: 'com.example.secondApp',
  );
}
